### PR TITLE
Update Program.cs

### PR DESCRIPTION
**Pull request by sathiyan-dev**
This is so good.

### CODE REVIEW

**Comment by sathiyan-dev** [comment]
Is it okay to commit.

**Comment by SathiyanRajendran** [comment]
Would you change to lokiverse world instead of you commit now.

**Comment by sathiyan-dev** [comment]
> Would you change to lokiverse world instead of you commit now.

Yes I can!

**Review by SathiyanRajendran — COMMENTED** [review]
Good Like it.

**Pull request merged**
